CREATE TABLE blueprint_t (
	id INT PRIMARY KEY AUTO_INCREMENT,
	name VARCHAR(100) DEFAULT "Untitled Project",
	user_id INT NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY (user_id) REFERENCES user_t(id)
);